apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-mysql-single-pod
  labels:
    app: wordpress-mysql-single-pod
spec:
  selector:
    matchLabels:
      app: wordpress-mysql-single-pod
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress-mysql-single-pod
    spec:
      containers:
      - image: mysql:8.0
        name: mysql
        env:
        - name: MYSQL_RANDOM_ROOT_PASSWORD
          value: '1'
        - name: MYSQL_DATABASE
          value: wpdb
        - name: MYSQL_USER
          value: wp-user
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      - image: wordpress:6.0.0-php8.1-apache
        name: wordpress
        env:
        - name: WORDPRESS_DB_HOST
          value: 127.0.0.1
        - name: WORDPRESS_DB_USER
          value: wp-user
        - name: WORDPRESS_DB_NAME
          value: wpdb
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        ports:
        - containerPort: 80
          name: wordpress
        volumeMounts:
        - name: wordpress-persistent-storage
          mountPath: /var/www/html
        - name: php-ini-cm-volume
          mountPath: /usr/local/etc/php/php.ini
          subPath: php.ini
      volumes:
      - name: wordpress-persistent-storage
        persistentVolumeClaim:
          claimName: wordpress-mysql-single-pod-wp-pv-claim
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: wordpress-mysql-single-pod-mysql-pv-claim
      - name: php-ini-cm-volume
        configMap:
          name: php-ini-cm
---
