apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-mysql-single-pod-wp-pv-claim
  labels:
    app: wordpress-mysql-single-pod
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---