apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: wordpress-mysql-single-pod
spec:
  ports:
    - port: 80
  selector:
    app: wordpress-mysql-single-pod
  type: LoadBalancer
---